# Generated by Django 4.2.6 on 2023-12-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
